[package]
name = "muta-codec-derive"
version = "0.2.0"
authors = ["Muta Dev <muta@nervos.org>"]
edition = "2018"
repository = "https://github.com/nervosnetwork/muta-utils"
license = "MIT"
description = "Muta fixed codec derive procedural macros."

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "1.0"

[dev-dependencies]
bytes = "0.5"
rand = "0.7"
rlp = "0.4"
muta-protocol = { git = "https://github.com/nervosnetwork/muta.git", rev = "0734799" } 
